### ISSUE TITLE
Investigate incompatibility with bootstrap-table v.1.15.x

### ISSUE THREAD

**Issue by ibot3** [agdsn/pycroft#325] opened 2019-08-07 20:11 UTC
There seems to be a problem with bootstrap-table in the version 1.15.3.
This issue prevents all table from being loaded.

This should be investigated. It might be required to create an issue for bootstrap-table.

**Comment by ibot3** [comment] 2019-08-10 12:58
Version 1.15.x brings some new features, for example support for checkboxes in a table.
This would allow us to improve the UI for some procedures.

**Comment by lukasjuhrich** [comment] 2020-06-29 08:16
I cannot reproduce that on my `yarn-test`-branch, where I upgraded everything – in particular,
- bootstrap to v4
- bootstrap-table to `1.16.0`

**Comment by ibot3** [comment] 2020-06-29 08:19
Maybe this has been fixed already or was/is a problem that comes together with bootstrap 3 or an other dependency.

**Comment by lukasjuhrich** [comment] 2020-07-16 01:49
Closing, BS4 is live, and in 13461417af77bc15244e73dba0940ea9b8972846 `bootstrap-table` is on `~1.16.0`

**Closed** 2020-07-16 01:49 UTC
Labels: bug, ui
