### ISSUE TITLE
BS4-Related UI problems

### ISSUE THREAD

**Issue by ibot3** [agdsn/pycroft#393] opened 2020-07-23 17:27 UTC
The update to Bootstrap 4 broke the UI at several points.
This should be fixed. Some point are:

- [ ] Bank account table too wide
- [x] Button groups (for example MAC vendor or when creating a new transaction)
- [x] Form Buttons and Checkboxes are not aligned/positioned correclty
- [x] No log tab selected by default (easy fix, already done for other tabbed layouts)
- [ ] Room patchports are displayed a bit confusing

**Comment by lukasjuhrich** [comment] 2020-10-06 18:20
@ibot3 What's the state of this? I'm kind of hoping that some of these have been fixed already.

**Comment by ibot3** [comment] 2020-10-06 20:15
I fixed the form related issues on the onlinereg branch.

**Comment by lukasjuhrich** [comment] 2021-03-29 02:10
I cannot reproduce the first point. It has perfect horizontal scrolling on all sizes.

**Comment by lukasjuhrich** [comment] 2021-03-29 02:11
Also, This list might  be expanded in context of work on #448

**Comment by lukasjuhrich** [comment] 2021-08-13 14:11
> Room patchports are displayed a bit confusing

I'm not sure what you mean by that.  In my room, everything looks as it should (modulo `¿` censoring):
![image](https://user-images.githubusercontent.com/10060406/129370168-25d17987-b4a0-494f-a0ac-f40a5182c551.png)

**Comment by lukasjuhrich** [comment] 2021-08-13 14:13
Please adapt the task list according to the comments and close this issue if everything is resolved.

**Comment by ibot3** [comment] 2021-08-14 12:42
I do not rember anymore what the real problem was. However, I will create a separate issue for it, because the room overview could be better.

**Comment by lukasjuhrich** [comment] 2021-08-14 20:55
In that case I'm closing this one.

**Closed by lukasjuhrich** 2021-08-14 20:55 UTC
Labels: bug, ui, easy task
