### ISSUE TITLE
Versenden der Begrüßungsmails

### ISSUE THREAD

**Issue by lukasjuhrich** [agdsn/pycroft#23] opened 2016-09-28 17:08 UTC
> ### Redmine metadata
> 
> | Attribute | Value |
> | --- | --- |
> | done_ratio | 0 |
> | status | New |
> | start_date | 2012/06/30 |
> | created_on | 2012/06/30 23:18:18 +0200 |
> | author | @cooox |
> | priority | Normal |
> | updated_on | 2016/09/18 19:02:05 +0200 |
> | tracker | Feature |
> | asigned_to | None |

---

Mail wird bei Anlegen eines Accounts an <login>@wh2.tu-dresden.de zugestellt.

Siehe legacy-agdsn-config:source:greetmail.py
## 

_This issue has been automatically imported from redmine on 2016-09-28 19:08:37.044211_

**Comment by lukasjuhrich** [comment] 2016-10-01 13:50
by the way, the referenced script currently starts the following way:

```python
#!/usr/bin/env python
#
# greetmail
#
# ported from python, 2009-07-07 --mmarx


import sys
import email
import smtplib
from email.Utils import formatdate
from email.MIMEText import MIMEText


from agdsn import conf
import agdsn.conf.mail
import agdsn.pwd

# This whole lib is a MESS, just like Jeb!
# deactivated to stop sending misinformation
sys.exit(0)

# …
```

**Comment by ibot3** [comment] 2019-08-23 13:30
Closing as duplicate of #267

**Closed by ibot3** 2019-08-23 13:30 UTC
Labels: duplicate, feature
